import './inventory.css';
import './inventoryComparison.css';
import type { CharacterProgress } from '../character/characterCreator';
import { GEM_BY_ID } from '../equipment/refinementConfig';
import {
  ITEM_CATEGORY_LABELS, ITEM_RARITY_LABELS, ensureInventoryState, equipItem, equipmentTotalStats, getItem, inventorySlotsUsed, normalizeEnhancement, organizeInventory, unequipItem,
  type EquipmentSlot, type ItemCategory, type ItemEnhancementData, type ItemStats,
} from './itemCatalog';

type InventoryCallbacks = { getHp: () => number; setHp: (value: number) => void; onChanged: () => void; notify: (message: string) => void };
type Selection = { source: 'inventory'; itemId: string; index: number } | { source: 'equipment'; itemId: string; slot: EquipmentSlot } | null;
const TABS: Array<{ id: ItemCategory | 'all'; icon: string }> = [
  { id: 'all', icon: '▦' }, { id: 'consumable', icon: '✚' }, { id: 'material', icon: '◆' }, { id: 'weapon', icon: '⚔' }, { id: 'equipment', icon: '♜' }, { id: 'accessory', icon: '◇' },
];
const EQUIPMENT_SLOTS: Array<{ id: EquipmentSlot; label: string; icon: string }> = [
  { id: 'head', label: 'Cabeça', icon: '◒' }, { id: 'armor', label: 'Peitoral', icon: '♜' }, { id: 'legs', label: 'Pernas', icon: '▥' }, { id: 'boots', label: 'Botas', icon: '⌄' }, { id: 'weapon', label: 'Arma', icon: '⚔' }, { id: 'accessory1', label: 'Acessório I', icon: '◇' }, { id: 'accessory2', label: 'Acessório II', icon: '◇' },
];

function targetSlot(progress: CharacterProgress, itemId: string): EquipmentSlot | null {
  const state = ensureInventoryState(progress), item = getItem(itemId); if (!item?.equipSlot) return null;
  if (item.equipSlot === 'accessory') return state.equipment.accessory1 ? 'accessory2' : 'accessory1';
  return item.equipSlot;
}
function displayName(name: string, meta?: ItemEnhancementData | null) { const refine = normalizeEnhancement(meta).refine; return `${name}${refine > 0 ? ` +${refine}` : ''}`; }
function statsRows(stats: ItemStats) { const rows: string[] = []; if (stats.attack) rows.push(`Ataque +${stats.attack}`); if (stats.defense) rows.push(`Defesa +${stats.defense}`); if (stats.maxHp) rows.push(`HP máximo +${stats.maxHp}`); return rows; }
function comparisonHtml(progress: CharacterProgress, itemId: string, incoming?: ItemEnhancementData) {
  const state = ensureInventoryState(progress), slot = targetSlot(state as unknown as CharacterProgress, itemId); if (!slot) return '';
  const currentId = state.equipment[slot], current = currentId ? getItem(currentId) : undefined, currentMeta = state.equipmentEnhancements?.[slot];
  const nextStats = equipmentTotalStats(itemId, slot, incoming), currentStats = equipmentTotalStats(currentId, slot, currentMeta);
  const rows: Array<[keyof ItemStats, string]> = [['attack','Ataque'],['defense','Defesa'],['maxHp','HP máximo']];
  const body = rows.map(([stat,name]) => { const delta = (nextStats[stat] ?? 0) - (currentStats[stat] ?? 0), cls = delta > 0 ? 'positive' : delta < 0 ? 'negative' : 'neutral', text = delta > 0 ? `▲ +${delta}` : delta < 0 ? `▼ ${delta}` : '— 0'; return `<div class="comparison-row ${cls}"><span>${name}</span><strong>${text}</strong></div>`; }).join('');
  return `<div class="detail-comparison"><div class="detail-comparison-head"><span>Comparação</span><strong>${current ? displayName(current.name, currentMeta) : 'Slot vazio'}</strong></div><div class="detail-comparison-rows">${body}</div></div>`;
}

export function createInventory(progress: CharacterProgress, callbacks: InventoryCallbacks) {
  const state = ensureInventoryState(progress); let activeTab: ItemCategory | 'all' = 'all', search = ''; let selection: Selection = null;
  const root = document.createElement('div'); root.id = 'inventory-overlay'; root.className = 'inventory-hidden';
  root.innerHTML = `<div class="inventory-window" role="dialog" aria-label="Inventário"><header class="inventory-header"><div class="inventory-title-block"><span class="inventory-kicker">ASCENSION</span><h2>Inventário</h2><span id="inventory-capacity"></span></div><div class="inventory-header-actions"><label class="inventory-search"><span>⌕</span><input id="inventory-search" type="search" placeholder="Buscar item..." autocomplete="off" /></label><button id="inventory-sort" class="inventory-tool" type="button" title="Auto-organizar">↕ <span>Organizar</span></button><button id="inventory-close" class="inventory-close" type="button" aria-label="Fechar">×</button></div></header><nav id="inventory-tabs" class="inventory-tabs"></nav><div class="inventory-body"><main class="inventory-main"><div class="inventory-toolbar"><span id="inventory-filter-label"></span><span id="inventory-result-count"></span></div><div id="inventory-grid" class="inventory-grid"></div></main><aside class="inventory-side"><section class="equipment-card"><div class="panel-heading"><span>Equipado</span><small id="inventory-power"></small></div><div id="equipment-grid" class="equipment-grid"></div></section><section id="item-details" class="item-details"></section></aside></div><footer class="inventory-footer"><span>Toque em um item para ver os detalhes.</span><span><kbd>I</kbd> abrir/fechar · <kbd>Esc</kbd> fechar</span></footer></div>`;
  document.body.appendChild(root);
  const tabs = root.querySelector<HTMLElement>('#inventory-tabs')!, grid = root.querySelector<HTMLElement>('#inventory-grid')!, equipmentGrid = root.querySelector<HTMLElement>('#equipment-grid')!, details = root.querySelector<HTMLElement>('#item-details')!, capacity = root.querySelector<HTMLElement>('#inventory-capacity')!, filterLabel = root.querySelector<HTMLElement>('#inventory-filter-label')!, resultCount = root.querySelector<HTMLElement>('#inventory-result-count')!, power = root.querySelector<HTMLElement>('#inventory-power')!, searchInput = root.querySelector<HTMLInputElement>('#inventory-search')!;
  const setSelection = (next: Selection) => { selection = next; render(); };
  const removeAt = (index: number, quantity = 1) => { const stack = state.inventory[index]; if (!stack || stack.quantity < quantity) return false; stack.quantity -= quantity; if (stack.quantity <= 0) state.inventory.splice(index,1); return true; };

  const renderTabs = () => { tabs.replaceChildren(); for (const tab of TABS) { const button = document.createElement('button'); button.type = 'button'; button.className = `inventory-tab${activeTab === tab.id ? ' active' : ''}`; button.innerHTML = `<span>${tab.icon}</span><strong>${ITEM_CATEGORY_LABELS[tab.id]}</strong>`; button.addEventListener('click', () => { activeTab = tab.id; render(); }); tabs.appendChild(button); } };
  const renderGrid = () => {
    grid.replaceChildren();
    const stacks = state.inventory.map((stack,index) => ({ ...stack,index,item:getItem(stack.itemId) })).filter((entry) => entry.item).filter((entry) => activeTab === 'all' || entry.item!.category === activeTab).filter((entry) => !search || entry.item!.name.toLocaleLowerCase('pt-BR').includes(search));
    for (const entry of stacks) { const item = entry.item!, name = displayName(item.name, entry.enhancement), button = document.createElement('button'); button.type = 'button'; button.className = `inventory-slot rarity-${item.rarity}${selection?.source === 'inventory' && selection.index === entry.index ? ' selected' : ''}`; button.title = name; button.innerHTML = `<span class="slot-rarity"></span><span class="slot-icon">${item.icon}</span>${entry.quantity > 1 ? `<span class="slot-quantity">${entry.quantity}</span>` : ''}<span class="slot-name">${name}</span>`; button.addEventListener('click', () => setSelection({ source:'inventory', itemId:item.id, index:entry.index })); grid.appendChild(button); }
    if (activeTab === 'all' && !search) for (let i=0;i<Math.max(0,state.inventoryCapacity-state.inventory.length);i++){ const node=document.createElement('span'); node.className='inventory-slot empty'; node.innerHTML='<span class="empty-mark">·</span>'; grid.appendChild(node); }
    filterLabel.textContent = ITEM_CATEGORY_LABELS[activeTab]; resultCount.textContent = `${stacks.length} ${stacks.length === 1 ? 'pilha' : 'pilhas'}`;
  };
  const renderEquipment = () => {
    equipmentGrid.replaceChildren();
    for (const slot of EQUIPMENT_SLOTS) { const itemId=state.equipment[slot.id], item=itemId?getItem(itemId):undefined, meta=state.equipmentEnhancements?.[slot.id], button=document.createElement('button'); button.type='button'; button.className=`equipment-slot${item?` rarity-${item.rarity}`:''}${selection?.source==='equipment'&&selection.slot===slot.id?' selected':''}`; button.innerHTML=item?`<span class="equipment-icon">${item.icon}</span><span><small>${slot.label}</small><strong>${displayName(item.name,meta)}</strong></span>`:`<span class="equipment-icon empty-equip">${slot.icon}</span><span><small>${slot.label}</small><strong>Vazio</strong></span>`; if(item)button.addEventListener('click',()=>setSelection({source:'equipment',itemId:item.id,slot:slot.id})); equipmentGrid.appendChild(button); }
    power.textContent=`ATQ ${state.attack} · DEF ${state.defense}`;
  };
  const renderDetails = () => {
    if(!selection){details.innerHTML='<div class="details-empty"><span>◇</span><strong>Selecione um item</strong><p>As informações, atributos e ações aparecerão aqui.</p></div>';return;}
    const item=getItem(selection.itemId); if(!item){selection=null;renderDetails();return;}
    const isInventory=selection.source==='inventory', inventoryStack=isInventory?state.inventory[selection.index]:undefined;
    if(isInventory && (!inventoryStack || inventoryStack.itemId!==item.id)){selection=null;renderDetails();return;}
    const meta=isInventory?inventoryStack?.enhancement:state.equipmentEnhancements?.[selection.slot];
    const slot=isInventory?targetSlot(state as unknown as CharacterProgress,item.id):selection.slot;
    const effectiveStats=slot&&item.equipSlot?equipmentTotalStats(item.id,slot,meta):item.stats??{};
    const statLines=statsRows(effectiveStats), refine=normalizeEnhancement(meta).refine, gems=normalizeEnhancement(meta).gems.filter(Boolean).map((id)=>GEM_BY_ID[id!]).filter(Boolean);
    const canUse=isInventory&&(Boolean(item.heal)||Boolean(item.capacityBonus)), canEquip=isInventory&&Boolean(item.equipSlot), canUnequip=selection.source==='equipment';
    details.innerHTML=`<div class="detail-top rarity-${item.rarity}"><span class="detail-icon">${item.icon}</span><div><span class="detail-rarity">${ITEM_RARITY_LABELS[item.rarity]}</span><h3>${displayName(item.name,meta)}</h3><small>${ITEM_CATEGORY_LABELS[item.category]}</small></div></div><p class="detail-description">${item.description}</p>${refine>0?`<div class="detail-stats"><span>💠 Refino +${refine}</span></div>`:''}${gems.length?`<div class="detail-stats">${gems.map((gem)=>`<span>${gem.icon} ${gem.name}</span>`).join('')}</div>`:''}${statLines.length?`<div class="detail-stats">${statLines.map((row)=>`<span>${row}</span>`).join('')}</div>`:''}${item.heal?`<div class="detail-stats"><span>Recupera ${item.heal} HP</span></div>`:''}${item.capacityBonus?`<div class="detail-stats"><span>Inventário +${item.capacityBonus} slots permanentes</span><span>Capacidade atual: ${state.inventoryCapacity}/48</span></div>`:''}${canEquip?comparisonHtml(state as unknown as CharacterProgress,item.id,meta):''}<div class="detail-meta"><span>Valor base</span><strong>🪙 ${item.value}</strong></div><div class="detail-actions">${canUse?'<button id="detail-use" class="primary-action" type="button">Usar</button>':''}${canEquip?'<button id="detail-equip" class="primary-action" type="button">Equipar</button>':''}${canUnequip?'<button id="detail-unequip" class="primary-action" type="button">Desequipar</button>':''}${isInventory?'<button id="detail-discard" class="danger-action" type="button">Descartar 1</button>':''}</div>`;
    details.querySelector<HTMLButtonElement>('#detail-use')?.addEventListener('click',()=>{if(selection?.source!=='inventory')return;if(item.capacityBonus){if(state.inventoryCapacity>=48){callbacks.notify('Seu inventário já atingiu o limite atual de 48 slots.');return;}if(!removeAt(selection.index,1))return;const before=state.inventoryCapacity;state.inventoryCapacity=Math.min(48,state.inventoryCapacity+item.capacityBonus);callbacks.notify(`${item.name}: capacidade aumentada de ${before} para ${state.inventoryCapacity} slots.`);callbacks.onChanged();selection=null;render();return;}if(!item.heal)return;const hp=callbacks.getHp();if(hp>=state.maxHp){callbacks.notify('Seu HP já está cheio.');return;}if(!removeAt(selection.index,1))return;const next=Math.min(state.maxHp,hp+item.heal);state.hp=next;callbacks.setHp(next);callbacks.notify(`${item.name}: +${Math.round(next-hp)} HP.`);callbacks.onChanged();selection=null;render();});
    details.querySelector<HTMLButtonElement>('#detail-equip')?.addEventListener('click',()=>{if(selection?.source!=='inventory')return;const result=equipItem(state as unknown as CharacterProgress,item.id,selection.index);if(!result.ok){callbacks.notify(result.reason??'Não foi possível equipar.');return;}const hp=Math.min(callbacks.getHp(),state.maxHp);state.hp=hp;callbacks.setHp(hp);callbacks.notify(`${displayName(item.name,state.equipmentEnhancements?.[result.slot!])} equipado.`);callbacks.onChanged();selection={source:'equipment',itemId:item.id,slot:result.slot!};render();});
    details.querySelector<HTMLButtonElement>('#detail-unequip')?.addEventListener('click',()=>{if(selection?.source!=='equipment')return;const result=unequipItem(state as unknown as CharacterProgress,selection.slot);if(!result.ok){callbacks.notify(result.reason??'Não foi possível desequipar.');return;}const hp=Math.min(callbacks.getHp(),state.maxHp);state.hp=hp;callbacks.setHp(hp);callbacks.notify(`${item.name} guardado no inventário com seus aprimoramentos.`);callbacks.onChanged();selection=null;render();});
    details.querySelector<HTMLButtonElement>('#detail-discard')?.addEventListener('click',()=>{if(selection?.source!=='inventory'||!removeAt(selection.index,1))return;callbacks.notify(`1x ${displayName(item.name,meta)} descartado.`);callbacks.onChanged();selection=null;render();});
  };
  const render=()=>{renderTabs();renderGrid();renderEquipment();renderDetails();capacity.textContent=`${inventorySlotsUsed(state as unknown as CharacterProgress)} / ${state.inventoryCapacity} slots`;};
  const open=()=>{root.classList.remove('inventory-hidden');root.classList.add('inventory-visible');render();}, close=()=>{root.classList.add('inventory-hidden');root.classList.remove('inventory-visible');}, toggle=()=>root.classList.contains('inventory-hidden')?open():close();
  root.querySelector<HTMLButtonElement>('#inventory-close')!.addEventListener('click',close);root.querySelector<HTMLButtonElement>('#inventory-sort')!.addEventListener('click',()=>{organizeInventory(state as unknown as CharacterProgress);selection=null;callbacks.notify('Inventário organizado.');callbacks.onChanged();render();});searchInput.addEventListener('input',()=>{search=searchInput.value.trim().toLocaleLowerCase('pt-BR');render();});root.addEventListener('pointerdown',(event)=>{if(event.target===root)close();});window.addEventListener('keydown',(event)=>{if(event.key.toLowerCase()==='i'&&!event.repeat&&document.activeElement!==searchInput){event.preventDefault();toggle();}if(event.key==='Escape'&&!root.classList.contains('inventory-hidden'))close();});
  render(); return {root,open,close,toggle,refresh:render,isOpen:()=>!root.classList.contains('inventory-hidden')};
}
