import { getClassDefinition } from '../classes/classCatalog';
import type { SkillEffect, SkillStudioRecord } from './skillStudioTypes';

const STORAGE_KEY = 'ascension.skill-studio.v2';
const CHANGE_EVENT = 'ascension-skill-definitions-change';
type SkillFile = { version: 2; records: SkillStudioRecord[] };
const clone = <T>(value: T): T => typeof structuredClone === 'function' ? structuredClone(value) : JSON.parse(JSON.stringify(value)) as T;
const now = () => Date.now();
const effectId = (prefix: string) => `${prefix}-${Math.random().toString(36).slice(2,8)}`;

function damage(multiplier: number, radius?: number): SkillEffect { return { id: effectId('damage'), type: 'damage', baseValue: 0, scalingStat: 'attack', multiplier, durationMs: 0, chance: 1, ...(radius ? { radius } : {}) }; }
function legacyRecords(): SkillStudioRecord[] {
  const stamp = 1;
  const base = (record: Omit<SkillStudioRecord,'version'|'source'|'status'|'tags'|'createdAt'|'updatedAt'|'className'>): SkillStudioRecord => ({ ...record, version:2, source:'legacy', status:'published', className:getClassDefinition(record.classId).name, tags:[], createdAt:stamp, updatedAt:stamp });
  return [
    base({ id:'warrior.power_strike',key:'warrior.power_strike',numericId:1,classId:'warrior',slot:1,unlockLevel:1,name:'Golpe Poderoso',shortName:'Golpe',icon:'💥',description:'Um golpe pesado que causa 150% do Ataque em um alvo próximo.',kind:'melee',targeting:'enemy',animation:'slash',energyCost:20,cooldownMs:4000,castTimeMs:0,range:135,damageMultiplier:1.5,effectColor:0xf0b85d,effects:[damage(1.5)] }),
    base({ id:'warrior.charge',key:'warrior.charge',numericId:2,classId:'warrior',slot:2,unlockLevel:1,name:'Investida',shortName:'Investida',icon:'➤',description:'Avança rapidamente até um inimigo e causa 125% do Ataque.',kind:'charge',targeting:'enemy',animation:'slash',energyCost:25,cooldownMs:7000,castTimeMs:0,range:300,damageMultiplier:1.25,effectColor:0x79c9ff,effects:[{id:effectId('dash'),type:'dash',baseValue:0,scalingStat:'none',multiplier:1,durationMs:0,chance:1},damage(1.25)] }),
    base({ id:'warrior.whirlwind',key:'warrior.whirlwind',numericId:3,classId:'warrior',slot:3,unlockLevel:1,name:'Corte Circular',shortName:'Circular',icon:'🌀',description:'Gira a arma e atinge todos os monstros próximos com 110% do Ataque.',kind:'aoe',targeting:'area-self',animation:'slash',energyCost:35,cooldownMs:8000,castTimeMs:0,radius:165,damageMultiplier:1.1,effectColor:0xe9c760,effects:[damage(1.1,165)] }),
    base({ id:'warrior.war_cry',key:'warrior.war_cry',numericId:4,classId:'warrior',slot:4,unlockLevel:1,name:'Grito de Guerra',shortName:'Grito',icon:'🔥',description:'Aumenta o Ataque em 25% durante 8 segundos.',kind:'buff',targeting:'self',animation:'emote',energyCost:30,cooldownMs:14000,castTimeMs:0,buffAttackPercent:25,buffDurationMs:8000,effectColor:0xf39a45,effects:[{id:effectId('buff'),type:'buff-attack',baseValue:25,scalingStat:'none',multiplier:1,durationMs:8000,chance:1}] }),
    base({ id:'mage.arcane_bolt',key:'mage.arcane_bolt',numericId:5,classId:'mage',slot:1,unlockLevel:1,name:'Projétil Arcano',shortName:'Arcano',icon:'✨',description:'Dispara energia arcana a longa distância causando 135% do Ataque.',kind:'target',targeting:'enemy',animation:'spellcast',energyCost:16,cooldownMs:2200,castTimeMs:0,range:430,damageMultiplier:1.35,effectColor:0x8bc5ff,projectileKey:'arcane_bolt',projectileSpeed:760,effects:[damage(1.35)] }),
    base({ id:'mage.fireball',key:'mage.fireball',numericId:6,classId:'mage',slot:2,unlockLevel:1,name:'Bola de Fogo',shortName:'Fogo',icon:'🔥',description:'Concentra fogo mágico em um alvo distante causando 180% do Ataque.',kind:'target',targeting:'enemy',animation:'spellcast',energyCost:28,cooldownMs:6000,castTimeMs:0,range:450,damageMultiplier:1.8,effectColor:0xff914d,projectileKey:'fireball',projectileSpeed:680,effects:[damage(1.8)] }),
    base({ id:'mage.arcane_wave',key:'mage.arcane_wave',numericId:7,classId:'mage',slot:3,unlockLevel:1,name:'Onda Arcana',shortName:'Onda',icon:'🔵',description:'Libera uma onda de Mana ao redor do Mago e atinge todos os inimigos próximos.',kind:'aoe',targeting:'area-self',animation:'spellcast',energyCost:34,cooldownMs:8000,castTimeMs:0,radius:185,damageMultiplier:1.05,effectColor:0x6f9fff,effects:[damage(1.05,185)] }),
    base({ id:'mage.arcane_focus',key:'mage.arcane_focus',numericId:8,classId:'mage',slot:4,unlockLevel:1,name:'Foco Arcano',shortName:'Foco',icon:'🔮',description:'Amplifica a magia, aumentando o Ataque em 30% durante 10 segundos.',kind:'buff',targeting:'self',animation:'spellcast',energyCost:30,cooldownMs:15000,castTimeMs:0,buffAttackPercent:30,buffDurationMs:10000,effectColor:0xa277ff,effects:[{id:effectId('buff'),type:'buff-attack',baseValue:30,scalingStat:'none',multiplier:1,durationMs:10000,chance:1}] }),
  ];
}

function normalizeEffect(input: Partial<SkillEffect>): SkillEffect {
  return { id:String(input.id || effectId('effect')), type:input.type ?? 'damage', baseValue:Number(input.baseValue)||0, scalingStat:input.scalingStat ?? 'attack', multiplier:Number.isFinite(Number(input.multiplier)) ? Number(input.multiplier) : 1, durationMs:Math.max(0,Math.floor(Number(input.durationMs)||0)), chance:Math.max(0,Math.min(1,Number.isFinite(Number(input.chance)) ? Number(input.chance) : 1)), ...(Number.isFinite(Number(input.radius)) ? {radius:Math.max(0,Number(input.radius))}: {}) };
}
function normalizeRecord(input: Partial<SkillStudioRecord> & Pick<SkillStudioRecord,'key'|'numericId'|'name'>): SkillStudioRecord {
  const key=String(input.key || input.id || '').trim(); const fallback=legacyRecords().find((entry)=>entry.key===key) ?? legacyRecords()[0]; const classId=String(input.classId || fallback.classId);
  return { ...clone(fallback), ...input, version:2, id:key, key, numericId:Math.max(1,Math.floor(Number(input.numericId)||1)), source:input.source==='legacy'?'legacy':'custom', status:input.status ?? 'draft', classId, className:getClassDefinition(classId).name, slot:Math.max(1,Math.min(12,Math.floor(Number(input.slot)||1))), unlockLevel:Math.max(1,Math.floor(Number(input.unlockLevel)||1)), name:String(input.name||'Nova Habilidade'), shortName:String(input.shortName||input.name||'Skill').slice(0,20), icon:String(input.icon||'✦'), description:String(input.description||''), energyCost:Math.max(0,Number(input.energyCost)||0), cooldownMs:Math.max(0,Math.floor(Number(input.cooldownMs)||0)), castTimeMs:Math.max(0,Math.floor(Number(input.castTimeMs)||0)), effects:Array.isArray(input.effects)?input.effects.map(normalizeEffect):[], tags:Array.isArray(input.tags)?input.tags.map(String).filter(Boolean):[], createdAt:Number(input.createdAt)||now(), updatedAt:Number(input.updatedAt)||now() };
}
function writeFile(file:SkillFile,notify=true){localStorage.setItem(STORAGE_KEY,JSON.stringify(file));if(notify)window.dispatchEvent(new CustomEvent(CHANGE_EVENT));}
function readFile():SkillFile{let parsed:Partial<SkillFile>|null=null;try{parsed=JSON.parse(localStorage.getItem(STORAGE_KEY)??'null') as Partial<SkillFile>|null;}catch{parsed=null;}const source=Array.isArray(parsed?.records)?parsed!.records!:[];const records=source.map((record)=>normalizeRecord(record));let changed=!source.length||parsed?.version!==2;for(const legacy of legacyRecords())if(!records.some((entry)=>entry.key===legacy.key)){records.push(legacy);changed=true;}records.sort((a,b)=>a.classId.localeCompare(b.classId)||a.slot-b.slot||a.numericId-b.numericId);const file={version:2 as const,records};if(changed)writeFile(file,false);return file;}

export function ensureSkillStudioMigration(){return readFile().records.map(clone);}
export function listSkillStudioRecords(){return readFile().records.map(clone);}
export function listPublishedSkills(){return listSkillStudioRecords().filter((entry)=>entry.status==='published');}
export function getSkillStudioRecord(key:string|null|undefined){const found=readFile().records.find((entry)=>entry.key===key);return found?clone(found):null;}
export function nextSkillNumericId(){return Math.max(0,...readFile().records.map((entry)=>entry.numericId))+1;}
export function createSkillStudioRecord(name='Nova Habilidade'):SkillStudioRecord{const numericId=nextSkillNumericId(),key=`skill_${numericId}`,base=clone(legacyRecords()[0]);return normalizeRecord({...base,id:key,key,numericId,name,shortName:name,source:'custom',status:'draft',classId:'warrior',slot:1,unlockLevel:1,icon:'✦',description:'',effects:[damage(1)],tags:[],createdAt:now(),updatedAt:now()});}
export function saveSkillStudioRecord(record:SkillStudioRecord){const file=readFile(),copy=normalizeRecord({...clone(record),id:record.key,updatedAt:now()});if(!copy.key)throw new Error('A habilidade precisa de uma chave interna.');const keyCollision=file.records.find((entry)=>entry.key===copy.key&&entry.numericId!==copy.numericId);if(keyCollision)throw new Error(`A chave ${copy.key} já está em uso.`);const idCollision=file.records.find((entry)=>entry.numericId===copy.numericId&&entry.key!==copy.key);if(idCollision)throw new Error(`Skill ID #${copy.numericId} já está em uso.`);const index=file.records.findIndex((entry)=>entry.numericId===copy.numericId);if(index>=0)file.records[index]=copy;else file.records.push(copy);writeFile(file);return clone(copy);}
export function duplicateSkillStudioRecord(recordOrKey:SkillStudioRecord|string){const source=typeof recordOrKey==='string'?getSkillStudioRecord(recordOrKey):clone(recordOrKey);if(!source)return null;const key=`${source.key}_copy_${Date.now().toString(36)}`;return saveSkillStudioRecord(normalizeRecord({...source,id:key,key,numericId:nextSkillNumericId(),name:`${source.name} - Cópia`,source:'custom',status:'draft',createdAt:now(),updatedAt:now()}));}
export function deleteSkillStudioRecord(key:string){const file=readFile(),target=file.records.find((entry)=>entry.key===key);if(!target)return false;if(target.source==='legacy')throw new Error('Skills migradas não podem ser apagadas; desative-as para preservar compatibilidade.');file.records=file.records.filter((entry)=>entry.key!==key);writeFile(file);return true;}
export function onSkillDefinitionsChange(listener:()=>void){window.addEventListener(CHANGE_EVENT,listener);return()=>window.removeEventListener(CHANGE_EVENT,listener);}
