import './style.css';
import './game/game.css';
import './character/characterSheetHud.css';
import './crafting/craftingUi.css';
import './settings/gameMenuHud.css';
import './chat/chatPauseProxy.css';
import './guild/guildPauseProxy.css';
import './guild/guildHud.css';
import './map/mapAutoRoute.css';
import { prepareChatBootstrap } from './chat/chatBootstrap';
import { prepareGuildBootstrap } from './guild/guildBootstrap';
import { startGame } from './game/runtime';
import './game/responsive.css';
import './game/desktopHudV2.css';
import './game/desktopHudReference.css';
import './game/desktopHudIdentity.css';
import './game/desktopHudStep1.css';
import './game/desktopHudStage2.css';
import './game/desktopHudStage2Fix.css';
import './game/desktopHudStage3.css';
import './game/desktopHudStage3Fix.css';
import { installResponsiveUi } from './game/responsive';
import { installDesktopViewportMetrics } from './game/desktopViewport';
import { installDesktopPartyHudBridge } from './game/partyHudBridge';
import { installDesktopHudStage3 } from './game/desktopHudStage3';
import { installGameContextMenuGuard } from './game/contextMenuGuard';
import { prepareCameraZoom } from './game/cameraZoom';
import { installMapAutoRoute } from './map/mapAutoRoute';
import { installMarkerRuntime } from './map/markerRuntime';
import { installMinimapShape } from './map/minimapShape';
import { installMapSystemStage4Polish } from './map/mapSystemStage4Polish';
import { preparePublishedWorldRuntime } from './map/publishedMapRuntime';
import { subscribePublishedMap } from './map/publishedMapStore';
import { hydrateNpcDefinitionsIntoPalette } from './npc/npcStore';
import { installPublishedNpcRuntime } from './npc/npcRuntime';
import { hydrateMonsterDefinitionsIntoPalette } from './monsterEditor/monsterStore';
import { hydrateItemStudioRuntime } from './items/itemStudioStore';
import { installItemInventoryVisualIntegration } from './items/itemInventoryVisualIntegration';
import { ensureDefaultGatheringTools } from './gathering/gatheringToolMigration';
import { ensureCollectibleMigration } from './gathering/collectibleStore';

export async function startGameApp() {
  installResponsiveUi();
  installDesktopViewportMetrics();
  installGameContextMenuGuard();
  const cameraZoom = prepareCameraZoom();
  const chatBootstrap = prepareChatBootstrap();
  const guildBootstrap = prepareGuildBootstrap();
  hydrateItemStudioRuntime();
  ensureDefaultGatheringTools();
  installItemInventoryVisualIntegration();
  hydrateNpcDefinitionsIntoPalette();
  hydrateMonsterDefinitionsIntoPalette();
  ensureCollectibleMigration();
  await preparePublishedWorldRuntime();
  await installPublishedNpcRuntime();
  const unsubscribePublished = subscribePublishedMap(() => {
    sessionStorage.setItem('ascension.map.just-published.v1', '1');
    window.location.reload();
  });
  window.addEventListener('pagehide', unsubscribePublished, { once: true });

  return startGame().then(() => {
    if (!document.querySelector('#hud')) return;
    chatBootstrap.attach();
    guildBootstrap.attach({ beforeOpen: () => chatBootstrap.chat?.close() });
    installDesktopPartyHudBridge();
    installDesktopHudStage3();
    installMapSystemStage4Polish();
    installMarkerRuntime();
    installMinimapShape();
    installMapAutoRoute();
    cameraZoom.attach();
  });
}
